version: '3.8'

services:
  api:
    build: .
    ports:
      - ${API_PORT}:3000
    volumes:
      - .:/api
    restart: always
    depends_on:
      - mysql
    networks:
      - nest-network
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - mysql-vol:/var/lib/mysql
    ports:
      - ${MYSQL_HOST_PORT}:${MYSQL_PORT}
    networks:
      - nest-network

volumes:
  mysql-vol:
    driver: local

networks:
  nest-network:
    driver: bridge